//subjectarea 1
function setOptions1(chosen)
{
var selbox1 = document.frmSubmit.specialization;

selbox1.options.length = 1;

if(document.frmSubmit.subsubject.value == "Other")
{
	document.frmSubmit.otherspecialization.disabled = false;
}
else
{
	document.frmSubmit.otherspecialization.disabled = true;
}
if (chosen == " ") {
selbox1.options[selbox1.options.length] = new Option('Please select the level',' ');
} if (chosen == "Lif-Agriculture") {	selbox1.options[selbox1.options.length] = new Option('Agribusiness','Agribusiness');
	selbox1.options[selbox1.options.length] = new Option('Agricultural Entomology','Agricultural Entomology');
	selbox1.options[selbox1.options.length] = new Option('Agriculture','Agriculture');
	selbox1.options[selbox1.options.length] = new Option('Agroecology','Agroecology');
	selbox1.options[selbox1.options.length] = new Option('Agrology','Agrology');
	selbox1.options[selbox1.options.length] = new Option('Agronomy','Agronomy');
	selbox1.options[selbox1.options.length] = new Option('Animal Husbandry','Animal Husbandry');
	selbox1.options[selbox1.options.length] = new Option('Dairy Science','Dairy Science');
	selbox1.options[selbox1.options.length] = new Option('Enology','Enology');
	selbox1.options[selbox1.options.length] = new Option('Farming','Farming');
	selbox1.options[selbox1.options.length] = new Option('Fisheries/Aquaculture','Fisheries/Aquaculture');
	selbox1.options[selbox1.options.length] = new Option('Forestry','Forestry');
	selbox1.options[selbox1.options.length] = new Option('Horticulture','Horticulture');
	selbox1.options[selbox1.options.length] = new Option('Organic Farming','Organic Farming');
	selbox1.options[selbox1.options.length] = new Option('Sustainable Agriculture','Sustainable Agriculture');
	selbox1.options[selbox1.options.length] = new Option('Urban and Industrial Agriculture','Urban and Industrial Agriculture');
	selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Lif-Biochemistry") {	selbox1.options[selbox1.options.length] = new Option('Animal Biochemistry','Animal Biochemistry');
	selbox1.options[selbox1.options.length] = new Option('Enzymology','Enzymology');
	selbox1.options[selbox1.options.length] = new Option('General Biochemistry','General Biochemistry');
	selbox1.options[selbox1.options.length] = new Option('Metabolism','Metabolism');
	selbox1.options[selbox1.options.length] = new Option('Plant Biochemistry','Plant Biochemistry');
	selbox1.options[selbox1.options.length] = new Option('Proteomics/Protein Studies','Proteomics/Protein Studies');
	selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Lif-Bioengineering") {	selbox1.options[selbox1.options.length] = new Option('Bioengineering (Others)','Bioengineering (Others)');
	selbox1.options[selbox1.options.length] = new Option('Biomedical Engineering','Biomedical Engineering');
	selbox1.options[selbox1.options.length] = new Option('Biomimetics','Biomimetics');
	selbox1.options[selbox1.options.length] = new Option('Biomolecular Engineering','Biomolecular Engineering');
	selbox1.options[selbox1.options.length] = new Option('Bioprocess Engineering','Bioprocess Engineering');
	selbox1.options[selbox1.options.length] = new Option('Biotechnology','Biotechnology');
	selbox1.options[selbox1.options.length] = new Option('Cellular Engineering','Cellular Engineering');
	selbox1.options[selbox1.options.length] = new Option('Tissue Engineering ','Tissue Engineering ');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Lif-Biosciences") {	selbox1.options[selbox1.options.length] = new Option('Anatomy','Anatomy');
	selbox1.options[selbox1.options.length] = new Option('Archeobiology','Archeobiology');
	selbox1.options[selbox1.options.length] = new Option('Bioinformatics','Bioinformatics');
	selbox1.options[selbox1.options.length] = new Option('Biomaterial Science','Biomaterial Science');
	selbox1.options[selbox1.options.length] = new Option('Biomedical Research (Experimental Medicine)','Biomedical Research (Experimental Medicine)');
	selbox1.options[selbox1.options.length] = new Option('Biomodeling','Biomodeling');
	selbox1.options[selbox1.options.length] = new Option('Biophysics','Biophysics');
	selbox1.options[selbox1.options.length] = new Option('Biosciences (Others)','Biosciences (Others)');
	selbox1.options[selbox1.options.length] = new Option('Biosciences Education','Biosciences Education');
	selbox1.options[selbox1.options.length] = new Option('Biostatistics','Biostatistics');
	selbox1.options[selbox1.options.length] = new Option('Cancer Research','Cancer Research');
	selbox1.options[selbox1.options.length] = new Option('Cell Biology','Cell Biology');
	selbox1.options[selbox1.options.length] = new Option('Chronobiology','Chronobiology');
	selbox1.options[selbox1.options.length] = new Option('Cognitive Science','Cognitive Science');
	selbox1.options[selbox1.options.length] = new Option('Computational Biology','Computational Biology');
	selbox1.options[selbox1.options.length] = new Option('Dental Research','Dental Research');
	selbox1.options[selbox1.options.length] = new Option('Developmental Biology','Developmental Biology');
	selbox1.options[selbox1.options.length] = new Option('Embryology','Embryology');
	selbox1.options[selbox1.options.length] = new Option('Entomology','Entomology');
	selbox1.options[selbox1.options.length] = new Option('Evolutionary Biology','Evolutionary Biology');
	selbox1.options[selbox1.options.length] = new Option('Food Sciences','Food Sciences');
	selbox1.options[selbox1.options.length] = new Option('Forensic biosciences','Forensic biosciences');
	selbox1.options[selbox1.options.length] = new Option('General/Molecular Pathology','General/Molecular Pathology');
	selbox1.options[selbox1.options.length] = new Option('Immunology','Immunology');
	selbox1.options[selbox1.options.length] = new Option('Marine Sciences','Marine Sciences');
	selbox1.options[selbox1.options.length] = new Option('Metabolomics','Metabolomics');
	selbox1.options[selbox1.options.length] = new Option('Molecular Biology','Molecular Biology');
	selbox1.options[selbox1.options.length] = new Option('Paleobiology','Paleobiology');
	selbox1.options[selbox1.options.length] = new Option('Structural Biology','Structural Biology');
	selbox1.options[selbox1.options.length] = new Option('Taxonomy','Taxonomy');
	selbox1.options[selbox1.options.length] = new Option('Toxicology','Toxicology');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Lif-Botany") {	selbox1.options[selbox1.options.length] = new Option('Botany','Botany');
	selbox1.options[selbox1.options.length] = new Option('Phycology','Phycology');
	selbox1.options[selbox1.options.length] = new Option('Plant anatomy/Phytoanatomy','Plant anatomy/Phytoanatomy');
	selbox1.options[selbox1.options.length] = new Option('Plant chemistry/Phytochemistry','Plant chemistry/Phytochemistry');
	selbox1.options[selbox1.options.length] = new Option('Plant genetics/Phytogenetics','Plant genetics/Phytogenetics');
	selbox1.options[selbox1.options.length] = new Option('Plant pathology/Phytopathology','Plant pathology/Phytopathology');
	selbox1.options[selbox1.options.length] = new Option('Plant Physiology/Phytophysiology','Plant Physiology/Phytophysiology');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Lif-Environmental Biosciences") {	selbox1.options[selbox1.options.length] = new Option('Biosphere Sciences','Biosphere Sciences');
	selbox1.options[selbox1.options.length] = new Option('Conservation (Habitat, Wildlife, Species, Water)','Conservation (Habitat, Wildlife, Species, Water)');
	selbox1.options[selbox1.options.length] = new Option('Ecology','Ecology');
	selbox1.options[selbox1.options.length] = new Option('Environmental Biochemistry','Environmental Biochemistry');
	selbox1.options[selbox1.options.length] = new Option('Environmental Material Sciences','Environmental Material Sciences');
	selbox1.options[selbox1.options.length] = new Option('Environmental Resources','Environmental Resources');
	selbox1.options[selbox1.options.length] = new Option('Environmental Toxicology','Environmental Toxicology');
	selbox1.options[selbox1.options.length] = new Option('Paleontology','Paleontology');
	selbox1.options[selbox1.options.length] = new Option('Soil Sciences','Soil Sciences');
	selbox1.options[selbox1.options.length] = new Option('Waste Management','Waste Management');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Lif-Genetics") {	selbox1.options[selbox1.options.length] = new Option('Applied Genetics','Applied Genetics');
	selbox1.options[selbox1.options.length] = new Option('Epigenetics','Epigenetics');
	selbox1.options[selbox1.options.length] = new Option('Genetic Engineering','Genetic Engineering');
	selbox1.options[selbox1.options.length] = new Option('Genetics','Genetics');
	selbox1.options[selbox1.options.length] = new Option('Genomics','Genomics');
	selbox1.options[selbox1.options.length] = new Option('Nucleic Acid Research','Nucleic Acid Research');
	selbox1.options[selbox1.options.length] = new Option('Phylogenetics','Phylogenetics');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Lif-Microbiology") {	selbox1.options[selbox1.options.length] = new Option('Agricultural Microbiology','Agricultural Microbiology');
	selbox1.options[selbox1.options.length] = new Option('Bacteriology','Bacteriology');
	selbox1.options[selbox1.options.length] = new Option('Environmental Microbiology','Environmental Microbiology');
	selbox1.options[selbox1.options.length] = new Option('Food Microbiology','Food Microbiology');
	selbox1.options[selbox1.options.length] = new Option('Industrial Microbiology','Industrial Microbiology');
	selbox1.options[selbox1.options.length] = new Option('Medical Microbiology','Medical Microbiology');
	selbox1.options[selbox1.options.length] = new Option('Microbial Physiology','Microbial Physiology');
	selbox1.options[selbox1.options.length] = new Option('Microbiology','Microbiology');
	selbox1.options[selbox1.options.length] = new Option('Mycology','Mycology');
	selbox1.options[selbox1.options.length] = new Option('Parasitology','Parasitology');
	selbox1.options[selbox1.options.length] = new Option('Pharmaceutical Microbiology','Pharmaceutical Microbiology');
	selbox1.options[selbox1.options.length] = new Option('Soil Microbiology','Soil Microbiology');
	selbox1.options[selbox1.options.length] = new Option('Virology','Virology');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Lif-Neurosciences") {	selbox1.options[selbox1.options.length] = new Option('Behavioral Neuroscience','Behavioral Neuroscience');
	selbox1.options[selbox1.options.length] = new Option('Cellular Neuroscience','Cellular Neuroscience');
	selbox1.options[selbox1.options.length] = new Option('Cognitive Neuroscience','Cognitive Neuroscience');
	selbox1.options[selbox1.options.length] = new Option('Computational Neuroscience','Computational Neuroscience');
	selbox1.options[selbox1.options.length] = new Option('Developmental Neuroscience','Developmental Neuroscience');
	selbox1.options[selbox1.options.length] = new Option('Neurophysiology','Neurophysiology');
	selbox1.options[selbox1.options.length] = new Option('Neurosciences','Neurosciences');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Lif-Pharmaceutical Sciences") {	selbox1.options[selbox1.options.length] = new Option('Forensic Toxicology','Forensic Toxicology');
	selbox1.options[selbox1.options.length] = new Option('Pharmaceutical Chemistry','Pharmaceutical Chemistry');
	selbox1.options[selbox1.options.length] = new Option('Pharmaceutical Research','Pharmaceutical Research');
	selbox1.options[selbox1.options.length] = new Option('Pharmaceutical Sciences (Others)','Pharmaceutical Sciences (Others)');
	selbox1.options[selbox1.options.length] = new Option('Pharmaceutics','Pharmaceutics');
	selbox1.options[selbox1.options.length] = new Option('Pharmacogenomics','Pharmacogenomics');
	selbox1.options[selbox1.options.length] = new Option('Pharmacognosy','Pharmacognosy');
	selbox1.options[selbox1.options.length] = new Option('Pharmacy','Pharmacy');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Lif-Social Biosciences") {	selbox1.options[selbox1.options.length] = new Option('Anthropology','Anthropology');
	selbox1.options[selbox1.options.length] = new Option('Archeology','Archeology');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Lif-Zoology") {	selbox1.options[selbox1.options.length] = new Option('Acarology','Acarology');
	selbox1.options[selbox1.options.length] = new Option('Anthrozoology','Anthrozoology');
	selbox1.options[selbox1.options.length] = new Option('Arachnology','Arachnology');
	selbox1.options[selbox1.options.length] = new Option('Cetology','Cetology');
	selbox1.options[selbox1.options.length] = new Option('Ethology','Ethology');
	selbox1.options[selbox1.options.length] = new Option('Helminthology','Helminthology');
	selbox1.options[selbox1.options.length] = new Option('Herpetology','Herpetology');
	selbox1.options[selbox1.options.length] = new Option('Ichthyology','Ichthyology');
	selbox1.options[selbox1.options.length] = new Option('Malacology','Malacology');
	selbox1.options[selbox1.options.length] = new Option('Mammalogy','Mammalogy');
	selbox1.options[selbox1.options.length] = new Option('Nematology','Nematology');
	selbox1.options[selbox1.options.length] = new Option('Ornithology','Ornithology');
	selbox1.options[selbox1.options.length] = new Option('Protozoology','Protozoology');
	selbox1.options[selbox1.options.length] = new Option('Veterinary Sciences','Veterinary Sciences');
	selbox1.options[selbox1.options.length] = new Option('Zoography','Zoography');
	selbox1.options[selbox1.options.length] = new Option('Zoology','Zoology');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Phy-Astronomy/Astrophysics") {	selbox1.options[selbox1.options.length] = new Option('Astrobiology','Astrobiology');
	selbox1.options[selbox1.options.length] = new Option('Astronomy/Astrophysics (Others)','Astronomy/Astrophysics (Others)');
	selbox1.options[selbox1.options.length] = new Option('Astrophysics','Astrophysics');
	selbox1.options[selbox1.options.length] = new Option('Observational Astronomy','Observational Astronomy');
	selbox1.options[selbox1.options.length] = new Option('Theoretical Astronomy ','Theoretical Astronomy ');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Phy-Chemistry") {	selbox1.options[selbox1.options.length] = new Option('Analytical Chemistry','Analytical Chemistry');
	selbox1.options[selbox1.options.length] = new Option('Applied Chemistry','Applied Chemistry');
	selbox1.options[selbox1.options.length] = new Option('Astrochemistry','Astrochemistry');
	selbox1.options[selbox1.options.length] = new Option('Catalysis','Catalysis');
	selbox1.options[selbox1.options.length] = new Option('Chemical Education','Chemical Education');
	selbox1.options[selbox1.options.length] = new Option('Cheminformatics','Cheminformatics');
	selbox1.options[selbox1.options.length] = new Option('Chemistry (Others)','Chemistry (Others)');
	selbox1.options[selbox1.options.length] = new Option('Computational Chemistry','Computational Chemistry');
	selbox1.options[selbox1.options.length] = new Option('Coordination Chemistry ','Coordination Chemistry ');
	selbox1.options[selbox1.options.length] = new Option('Electrochemistry','Electrochemistry');
	selbox1.options[selbox1.options.length] = new Option('Environmental Chemistry','Environmental Chemistry');
	selbox1.options[selbox1.options.length] = new Option('Geochemistry','Geochemistry');
	selbox1.options[selbox1.options.length] = new Option('History of Chemistry','History of Chemistry');
	selbox1.options[selbox1.options.length] = new Option('Inorganic Chemistry','Inorganic Chemistry');
	selbox1.options[selbox1.options.length] = new Option('Interfacial Chemistry','Interfacial Chemistry');
	selbox1.options[selbox1.options.length] = new Option('Marine Chemistry','Marine Chemistry');
	selbox1.options[selbox1.options.length] = new Option('Mathematical Chemistry','Mathematical Chemistry');
	selbox1.options[selbox1.options.length] = new Option('Medicinal Chemistry','Medicinal Chemistry');
	selbox1.options[selbox1.options.length] = new Option('Nanochemistry','Nanochemistry');
	selbox1.options[selbox1.options.length] = new Option('Natural Products Chemistry','Natural Products Chemistry');
	selbox1.options[selbox1.options.length] = new Option('Nuclear Chemistry','Nuclear Chemistry');
	selbox1.options[selbox1.options.length] = new Option('Organic Chemistry ','Organic Chemistry ');
	selbox1.options[selbox1.options.length] = new Option('Organometallic Chemistry ','Organometallic Chemistry ');
	selbox1.options[selbox1.options.length] = new Option('Physical Chemistry ','Physical Chemistry ');
	selbox1.options[selbox1.options.length] = new Option('Polymer Chemistry','Polymer Chemistry');
	selbox1.options[selbox1.options.length] = new Option('Quantum Chemistry','Quantum Chemistry');
	selbox1.options[selbox1.options.length] = new Option('Radiochemistry','Radiochemistry');
	selbox1.options[selbox1.options.length] = new Option('Solid State Chemistry ','Solid State Chemistry ');
	selbox1.options[selbox1.options.length] = new Option('Spectroscopy','Spectroscopy');
	selbox1.options[selbox1.options.length] = new Option('Structural Chemistry ','Structural Chemistry ');
	selbox1.options[selbox1.options.length] = new Option('Theoretical Chemistry','Theoretical Chemistry');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Phy-Computer/Information Sciences") {	selbox1.options[selbox1.options.length] = new Option('Algebraic (symbolic) computation','Algebraic (symbolic) computation');
	selbox1.options[selbox1.options.length] = new Option('Algorithms','Algorithms');
	selbox1.options[selbox1.options.length] = new Option('Applied Information Sciences','Applied Information Sciences');
	selbox1.options[selbox1.options.length] = new Option('Artificial Intelligence','Artificial Intelligence');
	selbox1.options[selbox1.options.length] = new Option('Bioinformatics','Bioinformatics');
	selbox1.options[selbox1.options.length] = new Option('Biomodeling','Biomodeling');
	selbox1.options[selbox1.options.length] = new Option('Brain-computer Interface','Brain-computer Interface');
	selbox1.options[selbox1.options.length] = new Option('Cloud Computing','Cloud Computing');
	selbox1.options[selbox1.options.length] = new Option('Computational Finance','Computational Finance');
	selbox1.options[selbox1.options.length] = new Option('Computational Number Theory','Computational Number Theory');
	selbox1.options[selbox1.options.length] = new Option('Computer Aided Engineering (CAE)','Computer Aided Engineering (CAE)');
	selbox1.options[selbox1.options.length] = new Option('Computer and Society','Computer and Society');
	selbox1.options[selbox1.options.length] = new Option('Computer Architecture','Computer Architecture');
	selbox1.options[selbox1.options.length] = new Option('Computer Graphics','Computer Graphics');
	selbox1.options[selbox1.options.length] = new Option('Computer Hardware','Computer Hardware');
	selbox1.options[selbox1.options.length] = new Option('Computer Networking','Computer Networking');
	selbox1.options[selbox1.options.length] = new Option('Computer Science','Computer Science');
	selbox1.options[selbox1.options.length] = new Option('Computer Science Education','Computer Science Education');
	selbox1.options[selbox1.options.length] = new Option('Computer Software','Computer Software');
	selbox1.options[selbox1.options.length] = new Option('Computer Vision','Computer Vision');
	selbox1.options[selbox1.options.length] = new Option('Computer/Information Sciences (Others)','Computer/Information Sciences (Others)');
	selbox1.options[selbox1.options.length] = new Option('Cryptography','Cryptography');
	selbox1.options[selbox1.options.length] = new Option('Data management','Data management');
	selbox1.options[selbox1.options.length] = new Option('Data mining','Data mining');
	selbox1.options[selbox1.options.length] = new Option('Data Structures','Data Structures');
	selbox1.options[selbox1.options.length] = new Option('Database','Database');
	selbox1.options[selbox1.options.length] = new Option('Digital Forensics','Digital Forensics');
	selbox1.options[selbox1.options.length] = new Option('Distributed Computing','Distributed Computing');
	selbox1.options[selbox1.options.length] = new Option('History of Computer Science','History of Computer Science');
	selbox1.options[selbox1.options.length] = new Option('Human-Computer Interaction','Human-Computer Interaction');
	selbox1.options[selbox1.options.length] = new Option('Human-Machine Interface','Human-Machine Interface');
	selbox1.options[selbox1.options.length] = new Option('Image processing','Image processing');
	selbox1.options[selbox1.options.length] = new Option('Informatics','Informatics');
	selbox1.options[selbox1.options.length] = new Option('Information Management','Information Management');
	selbox1.options[selbox1.options.length] = new Option('Information Retrieval','Information Retrieval');
	selbox1.options[selbox1.options.length] = new Option('Information Security','Information Security');
	selbox1.options[selbox1.options.length] = new Option('Information Systems (Business Informatics)','Information Systems (Business Informatics)');
	selbox1.options[selbox1.options.length] = new Option('Information Theory','Information Theory');
	selbox1.options[selbox1.options.length] = new Option('Internet, World Wide Web','Internet, World Wide Web');
	selbox1.options[selbox1.options.length] = new Option('Knowledge Management','Knowledge Management');
	selbox1.options[selbox1.options.length] = new Option('Machine Learning','Machine Learning');
	selbox1.options[selbox1.options.length] = new Option('Multimedia, Hypermedia','Multimedia, Hypermedia');
	selbox1.options[selbox1.options.length] = new Option('Natural Language Processing (Computational Linguistics)','Natural Language Processing (Computational Linguistics)');
	selbox1.options[selbox1.options.length] = new Option('Neural Networks','Neural Networks');
	selbox1.options[selbox1.options.length] = new Option('Numerical Analysis','Numerical Analysis');
	selbox1.options[selbox1.options.length] = new Option('Operating Systems','Operating Systems');
	selbox1.options[selbox1.options.length] = new Option('Parallel Computing','Parallel Computing');
	selbox1.options[selbox1.options.length] = new Option('Programming Languages','Programming Languages');
	selbox1.options[selbox1.options.length] = new Option('Quantum Computing','Quantum Computing');
	selbox1.options[selbox1.options.length] = new Option('Scientific Computing (Computational Science)','Scientific Computing (Computational Science)');
	selbox1.options[selbox1.options.length] = new Option('Soft Computing','Soft Computing');
	selbox1.options[selbox1.options.length] = new Option('The Digital Humanities (Humanities Computing)','The Digital Humanities (Humanities Computing)');
	selbox1.options[selbox1.options.length] = new Option('Theory of Computation','Theory of Computation');
	selbox1.options[selbox1.options.length] = new Option('Ubiquitous Computing','Ubiquitous Computing');
	selbox1.options[selbox1.options.length] = new Option('Virtual Reality','Virtual Reality');
	selbox1.options[selbox1.options.length] = new Option('Wireless Computing (Mobile Computing)','Wireless Computing (Mobile Computing)');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Phy-Earth Sciences") {	selbox1.options[selbox1.options.length] = new Option('Atmospheric Sciences','Atmospheric Sciences');
	selbox1.options[selbox1.options.length] = new Option('Computational Earth Sciences','Computational Earth Sciences');
	selbox1.options[selbox1.options.length] = new Option('Earth Sciences (Others)','Earth Sciences (Others)');
	selbox1.options[selbox1.options.length] = new Option('Earth Sciences Education','Earth Sciences Education');
	selbox1.options[selbox1.options.length] = new Option('Engineering Geology','Engineering Geology');
	selbox1.options[selbox1.options.length] = new Option('Environmental Science','Environmental Science');
	selbox1.options[selbox1.options.length] = new Option('Gemology','Gemology');
	selbox1.options[selbox1.options.length] = new Option('Geochemistry','Geochemistry');
	selbox1.options[selbox1.options.length] = new Option('Geochronology','Geochronology');
	selbox1.options[selbox1.options.length] = new Option('Geodesy','Geodesy');
	selbox1.options[selbox1.options.length] = new Option('Geodynamics','Geodynamics');
	selbox1.options[selbox1.options.length] = new Option('Geography','Geography');
	selbox1.options[selbox1.options.length] = new Option('Geology','Geology');
	selbox1.options[selbox1.options.length] = new Option('Geomorphology','Geomorphology');
	selbox1.options[selbox1.options.length] = new Option('Geophysics','Geophysics');
	selbox1.options[selbox1.options.length] = new Option('Geostatistics','Geostatistics');
	selbox1.options[selbox1.options.length] = new Option('Glaciology','Glaciology');
	selbox1.options[selbox1.options.length] = new Option('History of Earth Sciences','History of Earth Sciences');
	selbox1.options[selbox1.options.length] = new Option('Hydrogeology','Hydrogeology');
	selbox1.options[selbox1.options.length] = new Option('Hydrology','Hydrology');
	selbox1.options[selbox1.options.length] = new Option('Meteorology','Meteorology');
	selbox1.options[selbox1.options.length] = new Option('Mineralogy ','Mineralogy ');
	selbox1.options[selbox1.options.length] = new Option('Oceanography','Oceanography');
	selbox1.options[selbox1.options.length] = new Option('Paleobiology','Paleobiology');
	selbox1.options[selbox1.options.length] = new Option('Paleontology','Paleontology');
	selbox1.options[selbox1.options.length] = new Option('Petroleum Geology','Petroleum Geology');
	selbox1.options[selbox1.options.length] = new Option('Petrology','Petrology');
	selbox1.options[selbox1.options.length] = new Option('Sedimentology','Sedimentology');
	selbox1.options[selbox1.options.length] = new Option('Seismology','Seismology');
	selbox1.options[selbox1.options.length] = new Option('Soil science','Soil science');
	selbox1.options[selbox1.options.length] = new Option('Speleology','Speleology');
	selbox1.options[selbox1.options.length] = new Option('Tectonics','Tectonics');
	selbox1.options[selbox1.options.length] = new Option('Volcanology','Volcanology');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Phy-Energy and power") {	selbox1.options[selbox1.options.length] = new Option('Energy (General)','Energy (General)');
	selbox1.options[selbox1.options.length] = new Option('Energy and Power (Others)','Energy and Power (Others)');
	selbox1.options[selbox1.options.length] = new Option('Energy Conservation','Energy Conservation');
	selbox1.options[selbox1.options.length] = new Option('Power Engineering','Power Engineering');
	selbox1.options[selbox1.options.length] = new Option('Renewable Energy/Alternate Sources','Renewable Energy/Alternate Sources');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Phy-Engineering") {	selbox1.options[selbox1.options.length] = new Option('Acoustical Engineering','Acoustical Engineering');
	selbox1.options[selbox1.options.length] = new Option('Aerospace/Aeronautical Engineering','Aerospace/Aeronautical Engineering');
	selbox1.options[selbox1.options.length] = new Option('Agricultural Engineering','Agricultural Engineering');
	selbox1.options[selbox1.options.length] = new Option('Architecture','Architecture');
	selbox1.options[selbox1.options.length] = new Option('Automotive Engineering','Automotive Engineering');
	selbox1.options[selbox1.options.length] = new Option('Bioengineering','Bioengineering');
	selbox1.options[selbox1.options.length] = new Option('Biomolecular Engineering','Biomolecular Engineering');
	selbox1.options[selbox1.options.length] = new Option('Biosensing','Biosensing');
	selbox1.options[selbox1.options.length] = new Option('Biotechnology','Biotechnology');
	selbox1.options[selbox1.options.length] = new Option('Chemical Engineering  ','Chemical Engineering  ');
	selbox1.options[selbox1.options.length] = new Option('Civil Engineering','Civil Engineering');
	selbox1.options[selbox1.options.length] = new Option('Computer-aided Design','Computer-aided Design');
	selbox1.options[selbox1.options.length] = new Option('Computer-aided Engineering','Computer-aided Engineering');
	selbox1.options[selbox1.options.length] = new Option('Control systems Engineering','Control systems Engineering');
	selbox1.options[selbox1.options.length] = new Option('Earthquake engineering','Earthquake engineering');
	selbox1.options[selbox1.options.length] = new Option('Ecological Engineering','Ecological Engineering');
	selbox1.options[selbox1.options.length] = new Option('Electrical Engineering','Electrical Engineering');
	selbox1.options[selbox1.options.length] = new Option('Electronics Engineering','Electronics Engineering');
	selbox1.options[selbox1.options.length] = new Option('Engineering (Others)','Engineering (Others)');
	selbox1.options[selbox1.options.length] = new Option('Engineering Design','Engineering Design');
	selbox1.options[selbox1.options.length] = new Option('Engineering Education','Engineering Education');
	selbox1.options[selbox1.options.length] = new Option('Engineering Physics','Engineering Physics');
	selbox1.options[selbox1.options.length] = new Option('Ergonomics','Ergonomics');
	selbox1.options[selbox1.options.length] = new Option('Food Engineering','Food Engineering');
	selbox1.options[selbox1.options.length] = new Option('Forensic Engineering','Forensic Engineering');
	selbox1.options[selbox1.options.length] = new Option('Geotechnical engineering','Geotechnical engineering');
	selbox1.options[selbox1.options.length] = new Option('Highway engineering','Highway engineering');
	selbox1.options[selbox1.options.length] = new Option('History of Engineering','History of Engineering');
	selbox1.options[selbox1.options.length] = new Option('Industrial Engineering','Industrial Engineering');
	selbox1.options[selbox1.options.length] = new Option('Instrumentation Engineering','Instrumentation Engineering');
	selbox1.options[selbox1.options.length] = new Option('Manufacturing Engineering','Manufacturing Engineering');
	selbox1.options[selbox1.options.length] = new Option('Materials Engineering','Materials Engineering');
	selbox1.options[selbox1.options.length] = new Option('Mechanical Engineering','Mechanical Engineering');
	selbox1.options[selbox1.options.length] = new Option('Mechatronics','Mechatronics');
	selbox1.options[selbox1.options.length] = new Option('Metrology','Metrology');
	selbox1.options[selbox1.options.length] = new Option('Mining','Mining');
	selbox1.options[selbox1.options.length] = new Option('Nanoengineering','Nanoengineering');
	selbox1.options[selbox1.options.length] = new Option('Nanotechnology','Nanotechnology');
	selbox1.options[selbox1.options.length] = new Option('Nuclear Engineering','Nuclear Engineering');
	selbox1.options[selbox1.options.length] = new Option('Ocean Engineering','Ocean Engineering');
	selbox1.options[selbox1.options.length] = new Option('Optical Engineering','Optical Engineering');
	selbox1.options[selbox1.options.length] = new Option('Petroleum Engineering','Petroleum Engineering');
	selbox1.options[selbox1.options.length] = new Option('Printing Technology','Printing Technology');
	selbox1.options[selbox1.options.length] = new Option('Process Engineering','Process Engineering');
	selbox1.options[selbox1.options.length] = new Option('Production/Manufacturing Engineering','Production/Manufacturing Engineering');
	selbox1.options[selbox1.options.length] = new Option('Quality Assurance Engineering','Quality Assurance Engineering');
	selbox1.options[selbox1.options.length] = new Option('Remote Sensing','Remote Sensing');
	selbox1.options[selbox1.options.length] = new Option('Robotics','Robotics');
	selbox1.options[selbox1.options.length] = new Option('Safety Engineering','Safety Engineering');
	selbox1.options[selbox1.options.length] = new Option('Semiconductor Lithography','Semiconductor Lithography');
	selbox1.options[selbox1.options.length] = new Option('Sensors','Sensors');
	selbox1.options[selbox1.options.length] = new Option('Signal Processing','Signal Processing');
	selbox1.options[selbox1.options.length] = new Option('Software Engineering','Software Engineering');
	selbox1.options[selbox1.options.length] = new Option('Sports Medicine & Technology','Sports Medicine & Technology');
	selbox1.options[selbox1.options.length] = new Option('Structural Engineering','Structural Engineering');
	selbox1.options[selbox1.options.length] = new Option('Telecommunication Engineering','Telecommunication Engineering');
	selbox1.options[selbox1.options.length] = new Option('Textile Engineering','Textile Engineering');
	selbox1.options[selbox1.options.length] = new Option('Thermal/refrigeration Engineering','Thermal/refrigeration Engineering');
	selbox1.options[selbox1.options.length] = new Option('Transportation engineering','Transportation engineering');
	selbox1.options[selbox1.options.length] = new Option('Urban and Industrial Agriculture','Urban and Industrial Agriculture');
	selbox1.options[selbox1.options.length] = new Option('Urban Engineering','Urban Engineering');
	selbox1.options[selbox1.options.length] = new Option('Vehicle Engineering','Vehicle Engineering');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Phy-Environmental Sciences") {	selbox1.options[selbox1.options.length] = new Option('Environmental Chemistry','Environmental Chemistry');
	selbox1.options[selbox1.options.length] = new Option('Environmental Engineering','Environmental Engineering');
	selbox1.options[selbox1.options.length] = new Option('Environmental Geology','Environmental Geology');
	selbox1.options[selbox1.options.length] = new Option('Environmental Material Sciences','Environmental Material Sciences');
	selbox1.options[selbox1.options.length] = new Option('Environmental Sciences (Others)','Environmental Sciences (Others)');
	selbox1.options[selbox1.options.length] = new Option('Environmental Sciences Education','Environmental Sciences Education');
	selbox1.options[selbox1.options.length] = new Option('Radioactive Contamination','Radioactive Contamination');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Phy-Material Science & Engineering") {	selbox1.options[selbox1.options.length] = new Option('Biomaterial Science','Biomaterial Science');
	selbox1.options[selbox1.options.length] = new Option('Ceramics and Glasses','Ceramics and Glasses');
	selbox1.options[selbox1.options.length] = new Option('Colloid and Interface Science','Colloid and Interface Science');
	selbox1.options[selbox1.options.length] = new Option('Composites','Composites');
	selbox1.options[selbox1.options.length] = new Option('Computational Materials Science','Computational Materials Science');
	selbox1.options[selbox1.options.length] = new Option('Electronic, Optical and Magnetic Materials','Electronic, Optical and Magnetic Materials');
	selbox1.options[selbox1.options.length] = new Option('Material Characterization and Instrumentation','Material Characterization and Instrumentation');
	selbox1.options[selbox1.options.length] = new Option('Material Science & Engineering (Others)','Material Science & Engineering (Others)');
	selbox1.options[selbox1.options.length] = new Option('Material Science Education','Material Science Education');
	selbox1.options[selbox1.options.length] = new Option('MEMS','MEMS');
	selbox1.options[selbox1.options.length] = new Option('Metallurgy','Metallurgy');
	selbox1.options[selbox1.options.length] = new Option('Metals and Alloys','Metals and Alloys');
	selbox1.options[selbox1.options.length] = new Option('Molecular Engineering ','Molecular Engineering ');
	selbox1.options[selbox1.options.length] = new Option('Nanomaterials','Nanomaterials');
	selbox1.options[selbox1.options.length] = new Option('Polymer Science and Engineering','Polymer Science and Engineering');
	selbox1.options[selbox1.options.length] = new Option('Superconductors','Superconductors');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Phy-Mathematics") {	selbox1.options[selbox1.options.length] = new Option('Algebra','Algebra');
	selbox1.options[selbox1.options.length] = new Option('Analysis','Analysis');
	selbox1.options[selbox1.options.length] = new Option('Applied Mathematics','Applied Mathematics');
	selbox1.options[selbox1.options.length] = new Option('Calculus','Calculus');
	selbox1.options[selbox1.options.length] = new Option('Computational Mathematics','Computational Mathematics');
	selbox1.options[selbox1.options.length] = new Option('Game Theory','Game Theory');
	selbox1.options[selbox1.options.length] = new Option('Geometry and Topology','Geometry and Topology');
	selbox1.options[selbox1.options.length] = new Option('History of Mathematics','History of Mathematics');
	selbox1.options[selbox1.options.length] = new Option('Logic and Foundations of Mathematics','Logic and Foundations of Mathematics');
	selbox1.options[selbox1.options.length] = new Option('Mathematics (Others)','Mathematics (Others)');
	selbox1.options[selbox1.options.length] = new Option('Mathematics Education','Mathematics Education');
	selbox1.options[selbox1.options.length] = new Option('Number Theory','Number Theory');
	selbox1.options[selbox1.options.length] = new Option('Probability Theory','Probability Theory');
	selbox1.options[selbox1.options.length] = new Option('Stochastic Processes','Stochastic Processes');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Phy-Physics") {	selbox1.options[selbox1.options.length] = new Option('Accelerator Physics','Accelerator Physics');
	selbox1.options[selbox1.options.length] = new Option('Acoustics','Acoustics');
	selbox1.options[selbox1.options.length] = new Option('Applied Physics','Applied Physics');
	selbox1.options[selbox1.options.length] = new Option('Astrophysics','Astrophysics');
	selbox1.options[selbox1.options.length] = new Option('Atomic, Molecular, and Optical Physics','Atomic, Molecular, and Optical Physics');
	selbox1.options[selbox1.options.length] = new Option('Biophysics','Biophysics');
	selbox1.options[selbox1.options.length] = new Option('Computational Physics','Computational Physics');
	selbox1.options[selbox1.options.length] = new Option('Condensed Matter Physics','Condensed Matter Physics');
	selbox1.options[selbox1.options.length] = new Option('Cryogenics','Cryogenics');
	selbox1.options[selbox1.options.length] = new Option('Crystal Physics','Crystal Physics');
	selbox1.options[selbox1.options.length] = new Option('Fluid Physics','Fluid Physics');
	selbox1.options[selbox1.options.length] = new Option('History of Physics','History of Physics');
	selbox1.options[selbox1.options.length] = new Option('Low Temperature Physics','Low Temperature Physics');
	selbox1.options[selbox1.options.length] = new Option('Magnetism & Electromagnetism','Magnetism & Electromagnetism');
	selbox1.options[selbox1.options.length] = new Option('Mathematical Physics','Mathematical Physics');
	selbox1.options[selbox1.options.length] = new Option('Mechanics','Mechanics');
	selbox1.options[selbox1.options.length] = new Option('Medical Physics','Medical Physics');
	selbox1.options[selbox1.options.length] = new Option('Molecular Physics','Molecular Physics');
	selbox1.options[selbox1.options.length] = new Option('Newtonian Dynamics','Newtonian Dynamics');
	selbox1.options[selbox1.options.length] = new Option('Nonlinear and Statistical Physics','Nonlinear and Statistical Physics');
	selbox1.options[selbox1.options.length] = new Option('Nuclear and High-energy Physics','Nuclear and High-energy Physics');
	selbox1.options[selbox1.options.length] = new Option('Optics','Optics');
	selbox1.options[selbox1.options.length] = new Option('Particle Physics','Particle Physics');
	selbox1.options[selbox1.options.length] = new Option('Physics (Others)','Physics (Others)');
	selbox1.options[selbox1.options.length] = new Option('Physics Education','Physics Education');
	selbox1.options[selbox1.options.length] = new Option('Plasma Physics/Chemistry','Plasma Physics/Chemistry');
	selbox1.options[selbox1.options.length] = new Option('Quantum Physics','Quantum Physics');
	selbox1.options[selbox1.options.length] = new Option('Rheology','Rheology');
	selbox1.options[selbox1.options.length] = new Option('Semiconductor Physics','Semiconductor Physics');
	selbox1.options[selbox1.options.length] = new Option('Solid Mechanics','Solid Mechanics');
	selbox1.options[selbox1.options.length] = new Option('Theoretical Physics','Theoretical Physics');
	selbox1.options[selbox1.options.length] = new Option('Thermodynamics','Thermodynamics');
	selbox1.options[selbox1.options.length] = new Option('Tribology','Tribology');
	selbox1.options[selbox1.options.length] = new Option('Ultrafast Phenomenon','Ultrafast Phenomenon');
	selbox1.options[selbox1.options.length] = new Option('Vehicle Dynamics','Vehicle Dynamics');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Phy-Statistics") {	selbox1.options[selbox1.options.length] = new Option('Computational Statistics','Computational Statistics');
	selbox1.options[selbox1.options.length] = new Option('Design of Experiments','Design of Experiments');
	selbox1.options[selbox1.options.length] = new Option('Sampling and Survey','Sampling and Survey');
	selbox1.options[selbox1.options.length] = new Option('Statistical Modelling','Statistical Modelling');
	selbox1.options[selbox1.options.length] = new Option('Statistical Theory','Statistical Theory');
	selbox1.options[selbox1.options.length] = new Option('Statistics (Others)','Statistics (Others)');
	selbox1.options[selbox1.options.length] = new Option('Statistics Education','Statistics Education');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Phy-Systems Science") {	selbox1.options[selbox1.options.length] = new Option('Complex Systems','Complex Systems');
	selbox1.options[selbox1.options.length] = new Option('Control Theory','Control Theory');
	selbox1.options[selbox1.options.length] = new Option('Cybernetics','Cybernetics');
	selbox1.options[selbox1.options.length] = new Option('Operations Research','Operations Research');
	selbox1.options[selbox1.options.length] = new Option('Systems Dynamics','Systems Dynamics');
	selbox1.options[selbox1.options.length] = new Option('Systems Engineering','Systems Engineering');
	selbox1.options[selbox1.options.length] = new Option('Systems Science (Others)','Systems Science (Others)');
	selbox1.options[selbox1.options.length] = new Option('Systems Theory','Systems Theory');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Eco-Business Management") {	selbox1.options[selbox1.options.length] = new Option('Branding/Brand Management','Branding/Brand Management');
	selbox1.options[selbox1.options.length] = new Option('Business','Business');
	selbox1.options[selbox1.options.length] = new Option('Business Administration','Business Administration');
	selbox1.options[selbox1.options.length] = new Option('Business Ethics','Business Ethics');
	selbox1.options[selbox1.options.length] = new Option('Business Management (Others)','Business Management (Others)');
	selbox1.options[selbox1.options.length] = new Option('Corporate Social Responsibility','Corporate Social Responsibility');
	selbox1.options[selbox1.options.length] = new Option('Entrepreneurship','Entrepreneurship');
	selbox1.options[selbox1.options.length] = new Option('Hospitality','Hospitality');
	selbox1.options[selbox1.options.length] = new Option('Hotel Administration','Hotel Administration');
	selbox1.options[selbox1.options.length] = new Option('Human Resources','Human Resources');
	selbox1.options[selbox1.options.length] = new Option('International Business','International Business');
	selbox1.options[selbox1.options.length] = new Option('Management','Management');
	selbox1.options[selbox1.options.length] = new Option('Management Education','Management Education');
	selbox1.options[selbox1.options.length] = new Option('Management Information Systems','Management Information Systems');
	selbox1.options[selbox1.options.length] = new Option('Marketing','Marketing');
	selbox1.options[selbox1.options.length] = new Option('Operations Management','Operations Management');
	selbox1.options[selbox1.options.length] = new Option('Project Management','Project Management');
	selbox1.options[selbox1.options.length] = new Option('Risk Management','Risk Management');
	selbox1.options[selbox1.options.length] = new Option('Servicing','Servicing');
	selbox1.options[selbox1.options.length] = new Option('Strategy','Strategy');
	selbox1.options[selbox1.options.length] = new Option('Supply Chain Management','Supply Chain Management');
	selbox1.options[selbox1.options.length] = new Option('Technology Management','Technology Management');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Eco-Economics") {	selbox1.options[selbox1.options.length] = new Option('Accounting','Accounting');
	selbox1.options[selbox1.options.length] = new Option('Agricultural Economics','Agricultural Economics');
	selbox1.options[selbox1.options.length] = new Option('Banking','Banking');
	selbox1.options[selbox1.options.length] = new Option('Behavioral Economics','Behavioral Economics');
	selbox1.options[selbox1.options.length] = new Option('Computational Economics','Computational Economics');
	selbox1.options[selbox1.options.length] = new Option('Consumer Economics','Consumer Economics');
	selbox1.options[selbox1.options.length] = new Option('Corporate Finance','Corporate Finance');
	selbox1.options[selbox1.options.length] = new Option('Development Economics','Development Economics');
	selbox1.options[selbox1.options.length] = new Option('Ecological Economics','Ecological Economics');
	selbox1.options[selbox1.options.length] = new Option('E-Commerce','E-Commerce');
	selbox1.options[selbox1.options.length] = new Option('Econometrics','Econometrics');
	selbox1.options[selbox1.options.length] = new Option('Economic Geography','Economic Geography');
	selbox1.options[selbox1.options.length] = new Option('Economic History','Economic History');
	selbox1.options[selbox1.options.length] = new Option('Economic Sociology','Economic Sociology');
	selbox1.options[selbox1.options.length] = new Option('Economic Systems','Economic Systems');
	selbox1.options[selbox1.options.length] = new Option('Economics','Economics');
	selbox1.options[selbox1.options.length] = new Option('Economics Education','Economics Education');
	selbox1.options[selbox1.options.length] = new Option('Energy Economics','Energy Economics');
	selbox1.options[selbox1.options.length] = new Option('Entrepreneurial Economics','Entrepreneurial Economics');
	selbox1.options[selbox1.options.length] = new Option('Environmental Economics','Environmental Economics');
	selbox1.options[selbox1.options.length] = new Option('Evolutionary Economics','Evolutionary Economics');
	selbox1.options[selbox1.options.length] = new Option('Experimental Economics','Experimental Economics');
	selbox1.options[selbox1.options.length] = new Option('Feminist Economics','Feminist Economics');
	selbox1.options[selbox1.options.length] = new Option('Finance','Finance');
	selbox1.options[selbox1.options.length] = new Option('Financial Economics','Financial Economics');
	selbox1.options[selbox1.options.length] = new Option('Game Theory','Game Theory');
	selbox1.options[selbox1.options.length] = new Option('Green Economics','Green Economics');
	selbox1.options[selbox1.options.length] = new Option('Growth Economics','Growth Economics');
	selbox1.options[selbox1.options.length] = new Option('Health Economics','Health Economics');
	selbox1.options[selbox1.options.length] = new Option('Human Development Theory','Human Development Theory');
	selbox1.options[selbox1.options.length] = new Option('Industrial Organization','Industrial Organization');
	selbox1.options[selbox1.options.length] = new Option('Information Economics','Information Economics');
	selbox1.options[selbox1.options.length] = new Option('Institutional economics','Institutional economics');
	selbox1.options[selbox1.options.length] = new Option('Insurance','Insurance');
	selbox1.options[selbox1.options.length] = new Option('International Economics','International Economics');
	selbox1.options[selbox1.options.length] = new Option('International Trade','International Trade');
	selbox1.options[selbox1.options.length] = new Option('Islamic Economics','Islamic Economics');
	selbox1.options[selbox1.options.length] = new Option('Labor Economics','Labor Economics');
	selbox1.options[selbox1.options.length] = new Option('Law and Economics','Law and Economics');
	selbox1.options[selbox1.options.length] = new Option('Macroeconomics','Macroeconomics');
	selbox1.options[selbox1.options.length] = new Option('Managerial Economics','Managerial Economics');
	selbox1.options[selbox1.options.length] = new Option('Mathematical Economics','Mathematical Economics');
	selbox1.options[selbox1.options.length] = new Option('Microeconomics','Microeconomics');
	selbox1.options[selbox1.options.length] = new Option('Monetary Economics','Monetary Economics');
	selbox1.options[selbox1.options.length] = new Option('Neuroeconomics','Neuroeconomics');
	selbox1.options[selbox1.options.length] = new Option('Pharmacoeconomics','Pharmacoeconomics');
	selbox1.options[selbox1.options.length] = new Option('Political Economy','Political Economy');
	selbox1.options[selbox1.options.length] = new Option('Public Economics','Public Economics');
	selbox1.options[selbox1.options.length] = new Option('Public Finance','Public Finance');
	selbox1.options[selbox1.options.length] = new Option('Real Estate Economics','Real Estate Economics');
	selbox1.options[selbox1.options.length] = new Option('Resource Economics','Resource Economics');
	selbox1.options[selbox1.options.length] = new Option('Risk Analysis','Risk Analysis');
	selbox1.options[selbox1.options.length] = new Option('Socialist Economics','Socialist Economics');
	selbox1.options[selbox1.options.length] = new Option('Socioeconomics','Socioeconomics');
	selbox1.options[selbox1.options.length] = new Option('Tax','Tax');
	selbox1.options[selbox1.options.length] = new Option('Transport Economics','Transport Economics');
	selbox1.options[selbox1.options.length] = new Option('Welfare Economics','Welfare Economics');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Art-Design") {	selbox1.options[selbox1.options.length] = new Option('Design (Others)','Design (Others)');
	selbox1.options[selbox1.options.length] = new Option('Fashion','Fashion');
	selbox1.options[selbox1.options.length] = new Option('Graphic Design','Graphic Design');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Art-Disaster Studies") {	selbox1.options[selbox1.options.length] = new Option('Diaster Nursing','Diaster Nursing');
	selbox1.options[selbox1.options.length] = new Option('Disaster Management','Disaster Management');
	selbox1.options[selbox1.options.length] = new Option('Disaster Research','Disaster Research');
	selbox1.options[selbox1.options.length] = new Option('Disaster Studies (Others)','Disaster Studies (Others)');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Art-Education") {	
	selbox1.options[selbox1.options.length] = new Option('Critical Pedagogy','Critical Pedagogy');
	selbox1.options[selbox1.options.length] = new Option('Curriculum and Instruction','Curriculum and Instruction');
	selbox1.options[selbox1.options.length] = new Option('Distance Education','Distance Education');
	selbox1.options[selbox1.options.length] = new Option('Education','Education');
	selbox1.options[selbox1.options.length] = new Option('Educational Leadership','Educational Leadership');
	selbox1.options[selbox1.options.length] = new Option('Educational Philosophy','Educational Philosophy');
	selbox1.options[selbox1.options.length] = new Option('Educational Psychology','Educational Psychology');
	selbox1.options[selbox1.options.length] = new Option('Educational Reform/Education Policy','Educational Reform/Education Policy');
	selbox1.options[selbox1.options.length] = new Option('Educational Technology','Educational Technology');
	selbox1.options[selbox1.options.length] = new Option('Language Education','Language Education');
	selbox1.options[selbox1.options.length] = new Option('Medical Education','Medical Education');
	selbox1.options[selbox1.options.length] = new Option('Science Education','Science Education');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Art-Environmental Sciences") {	
	selbox1.options[selbox1.options.length] = new Option('Ecology','Ecology');
	selbox1.options[selbox1.options.length] = new Option('Environmenal Policy','Environmenal Policy');
	selbox1.options[selbox1.options.length] = new Option('Environmental Sociology','Environmental Sociology');
	selbox1.options[selbox1.options.length] = new Option('Environmental Studies (Others)','Environmental Studies (Others)');
	selbox1.options[selbox1.options.length] = new Option('Natural Resource Management','Natural Resource Management');
	selbox1.options[selbox1.options.length] = new Option('Sustainable Development','Sustainable Development');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Art-History") {	selbox1.options[selbox1.options.length] = new Option('Cultural History','Cultural History');
	selbox1.options[selbox1.options.length] = new Option('Diplomatic History','Diplomatic History');
	selbox1.options[selbox1.options.length] = new Option('History (Others)','History (Others)');
	selbox1.options[selbox1.options.length] = new Option('History of Economics','History of Economics');
	selbox1.options[selbox1.options.length] = new Option('World History','World History');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Art-Humanities") {	
	selbox1.options[selbox1.options.length] = new Option('Humanities (Others)','Humanities (Others)');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Art-Language & Linguistics") {	selbox1.options[selbox1.options.length] = new Option('Language & Linguistics (Others)','Language & Linguistics (Others)');
	selbox1.options[selbox1.options.length] = new Option('Language Education','Language Education');
	selbox1.options[selbox1.options.length] = new Option('Linguistics','Linguistics');
	selbox1.options[selbox1.options.length] = new Option('Phonetics & Phonology','Phonetics & Phonology');
	selbox1.options[selbox1.options.length] = new Option('Semantics & Syntax','Semantics & Syntax');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Art-Law") {	selbox1.options[selbox1.options.length] = new Option('Admiralty Law','Admiralty Law');
	selbox1.options[selbox1.options.length] = new Option('Animal Law/Animal Rights','Animal Law/Animal Rights');
	selbox1.options[selbox1.options.length] = new Option('Canon Law','Canon Law');
	selbox1.options[selbox1.options.length] = new Option('Civil Law','Civil Law');
	selbox1.options[selbox1.options.length] = new Option('Civil Procedure','Civil Procedure');
	selbox1.options[selbox1.options.length] = new Option('Comparative Law','Comparative Law');
	selbox1.options[selbox1.options.length] = new Option('Competition Law','Competition Law');
	selbox1.options[selbox1.options.length] = new Option('Constitutional Law','Constitutional Law');
	selbox1.options[selbox1.options.length] = new Option('Contracts','Contracts');
	selbox1.options[selbox1.options.length] = new Option('Corporate Law','Corporate Law');
	selbox1.options[selbox1.options.length] = new Option('Criminal Law','Criminal Law');
	selbox1.options[selbox1.options.length] = new Option('Environmental Law','Environmental Law');
	selbox1.options[selbox1.options.length] = new Option('Family Law','Family Law');
	selbox1.options[selbox1.options.length] = new Option('General Law','General Law');
	selbox1.options[selbox1.options.length] = new Option('Intellectual Property Law','Intellectual Property Law');
	selbox1.options[selbox1.options.length] = new Option('International Law','International Law');
	selbox1.options[selbox1.options.length] = new Option('Jurisprudence','Jurisprudence');
	selbox1.options[selbox1.options.length] = new Option('Labor Law','Labor Law');
	selbox1.options[selbox1.options.length] = new Option('Law (Others)','Law (Others)');
	selbox1.options[selbox1.options.length] = new Option('Maritime Law','Maritime Law');
	selbox1.options[selbox1.options.length] = new Option('Medical Law','Medical Law');
	selbox1.options[selbox1.options.length] = new Option('Paralegal Studies','Paralegal Studies');
	selbox1.options[selbox1.options.length] = new Option('Property Law','Property Law');
	selbox1.options[selbox1.options.length] = new Option('Tax Law','Tax Law');
	selbox1.options[selbox1.options.length] = new Option('Torts','Torts');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Art-Library and Museum Studies") {	selbox1.options[selbox1.options.length] = new Option('Archival Science','Archival Science');
	selbox1.options[selbox1.options.length] = new Option('Bibliometrics','Bibliometrics');
	selbox1.options[selbox1.options.length] = new Option('Information Science','Information Science');
	selbox1.options[selbox1.options.length] = new Option('Library and Museum Studies (Others)','Library and Museum Studies (Others)');
	selbox1.options[selbox1.options.length] = new Option('Library Science','Library Science');
	selbox1.options[selbox1.options.length] = new Option('Museology','Museology');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Art-Literature") {	selbox1.options[selbox1.options.length] = new Option('Comparative Literature','Comparative Literature');
	selbox1.options[selbox1.options.length] = new Option('Creative Writing','Creative Writing');
	selbox1.options[selbox1.options.length] = new Option('Literary Criticism','Literary Criticism');
	selbox1.options[selbox1.options.length] = new Option('Literature','Literature');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Art-Media/Communication") {	selbox1.options[selbox1.options.length] = new Option('Advertising','Advertising');
	selbox1.options[selbox1.options.length] = new Option('Business Documents','Business Documents');
	selbox1.options[selbox1.options.length] = new Option('Education/Career Documents','Education/Career Documents');
	selbox1.options[selbox1.options.length] = new Option('Journalism','Journalism');
	selbox1.options[selbox1.options.length] = new Option('Mass Media','Mass Media');
	selbox1.options[selbox1.options.length] = new Option('Media/Communication (Others)','Media/Communication (Others)');
	selbox1.options[selbox1.options.length] = new Option('Nonverbal Communication','Nonverbal Communication');
	selbox1.options[selbox1.options.length] = new Option('Public Relations','Public Relations');
	selbox1.options[selbox1.options.length] = new Option('Social Media','Social Media');
	selbox1.options[selbox1.options.length] = new Option('Speech Communication','Speech Communication');
	selbox1.options[selbox1.options.length] = new Option('Technical Writing','Technical Writing');
	selbox1.options[selbox1.options.length] = new Option('Translation','Translation');
	selbox1.options[selbox1.options.length] = new Option('Travel and Tourism','Travel and Tourism');
	selbox1.options[selbox1.options.length] = new Option('Web Content Development','Web Content Development');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Art-Performing Arts") {	selbox1.options[selbox1.options.length] = new Option('Dance','Dance');
	selbox1.options[selbox1.options.length] = new Option('Music','Music');
	selbox1.options[selbox1.options.length] = new Option('Performing Arts (Others)','Performing Arts (Others)');
	selbox1.options[selbox1.options.length] = new Option('Theater','Theater');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Art-Philosophy") {	
	selbox1.options[selbox1.options.length] = new Option('Aesthetics','Aesthetics');
	selbox1.options[selbox1.options.length] = new Option('Applied Philosophy','Applied Philosophy');
	selbox1.options[selbox1.options.length] = new Option('Epistemology','Epistemology');
	selbox1.options[selbox1.options.length] = new Option('Ethics','Ethics');
	selbox1.options[selbox1.options.length] = new Option('History of Philosophy','History of Philosophy');
	selbox1.options[selbox1.options.length] = new Option('Logic','Logic');
	selbox1.options[selbox1.options.length] = new Option('Metaphysics','Metaphysics');
	selbox1.options[selbox1.options.length] = new Option('Philosophical Traditions ','Philosophical Traditions ');
	selbox1.options[selbox1.options.length] = new Option('Philosophy (Others)','Philosophy (Others)');
	selbox1.options[selbox1.options.length] = new Option('Political Philosophy','Political Philosophy');
	selbox1.options[selbox1.options.length] = new Option('Social Philosophy','Social Philosophy');
	selbox1.options[selbox1.options.length] = new Option('Abnormal Psychology','Abnormal Psychology');
	selbox1.options[selbox1.options.length] = new Option('Applied Psychology','Applied Psychology');
	selbox1.options[selbox1.options.length] = new Option('Biological Psychology','Biological Psychology');
	selbox1.options[selbox1.options.length] = new Option('Child Psychology','Child Psychology');
	selbox1.options[selbox1.options.length] = new Option('Clinical Psychology','Clinical Psychology');
	selbox1.options[selbox1.options.length] = new Option('Cognitive Psychology','Cognitive Psychology');
	selbox1.options[selbox1.options.length] = new Option('Community Psychology','Community Psychology');
	selbox1.options[selbox1.options.length] = new Option('Comparative Psychology','Comparative Psychology');
	selbox1.options[selbox1.options.length] = new Option('Conservation Psychology','Conservation Psychology');
	selbox1.options[selbox1.options.length] = new Option('Consumer Psychology','Consumer Psychology');
	selbox1.options[selbox1.options.length] = new Option('Counseling Psychology','Counseling Psychology');
	selbox1.options[selbox1.options.length] = new Option('Cultural Psychology','Cultural Psychology');
	selbox1.options[selbox1.options.length] = new Option('Developmental Psychology','Developmental Psychology');
	selbox1.options[selbox1.options.length] = new Option('Differential Psychology','Differential Psychology');
	selbox1.options[selbox1.options.length] = new Option('Environmental Psychology','Environmental Psychology');
	selbox1.options[selbox1.options.length] = new Option('Evolutionary Psychology','Evolutionary Psychology');
	selbox1.options[selbox1.options.length] = new Option('Experimental Psychology','Experimental Psychology');
	selbox1.options[selbox1.options.length] = new Option('Forensic Psychiatry','Forensic Psychiatry');
	selbox1.options[selbox1.options.length] = new Option('General Psychology','General Psychology');
	selbox1.options[selbox1.options.length] = new Option('Health Psychology','Health Psychology');
	selbox1.options[selbox1.options.length] = new Option('Legal Psychology','Legal Psychology');
	selbox1.options[selbox1.options.length] = new Option('Media Psychology','Media Psychology');
	selbox1.options[selbox1.options.length] = new Option('Medical Psychology','Medical Psychology');
	selbox1.options[selbox1.options.length] = new Option('Military Psychology','Military Psychology');
	selbox1.options[selbox1.options.length] = new Option('Neuropsychology','Neuropsychology');
	selbox1.options[selbox1.options.length] = new Option('Occupational Health Psychology','Occupational Health Psychology');
	selbox1.options[selbox1.options.length] = new Option('Organizational Psychology','Organizational Psychology');
	selbox1.options[selbox1.options.length] = new Option('Parapsychology','Parapsychology');
	selbox1.options[selbox1.options.length] = new Option('Personality Psychology','Personality Psychology');
	selbox1.options[selbox1.options.length] = new Option('Political Psychology','Political Psychology');
	selbox1.options[selbox1.options.length] = new Option('Positive Psychology','Positive Psychology');
	selbox1.options[selbox1.options.length] = new Option('Psychology of Religion','Psychology of Religion');
	selbox1.options[selbox1.options.length] = new Option('Psychometrics','Psychometrics');
	selbox1.options[selbox1.options.length] = new Option('Psychophysics','Psychophysics');
	selbox1.options[selbox1.options.length] = new Option('Psychotherapy','Psychotherapy');
	selbox1.options[selbox1.options.length] = new Option('Quantitative Psychology','Quantitative Psychology');
	selbox1.options[selbox1.options.length] = new Option('School Psychology','School Psychology');
	selbox1.options[selbox1.options.length] = new Option('Social Psychology','Social Psychology');
	selbox1.options[selbox1.options.length] = new Option('Sport Psychology','Sport Psychology');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Art-Recreation and Sports") {	selbox1.options[selbox1.options.length] = new Option('Game/Toy Design','Game/Toy Design');
	selbox1.options[selbox1.options.length] = new Option('Physical Education','Physical Education');
	selbox1.options[selbox1.options.length] = new Option('Recreation and Sports (Others)','Recreation and Sports (Others)');
	selbox1.options[selbox1.options.length] = new Option('Sport Management/Coaching','Sport Management/Coaching');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Art-Religious Studies") {	selbox1.options[selbox1.options.length] = new Option('History of Religion','History of Religion');
	selbox1.options[selbox1.options.length] = new Option('Religious Studies (Others)','Religious Studies (Others)');
	selbox1.options[selbox1.options.length] = new Option('Sociology of Religion','Sociology of Religion');
	selbox1.options[selbox1.options.length] = new Option('Theology','Theology');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Art-Social Sciences") {	selbox1.options[selbox1.options.length] = new Option('Anthropology','Anthropology');
	selbox1.options[selbox1.options.length] = new Option('Archeology','Archeology');
	selbox1.options[selbox1.options.length] = new Option('Architecture','Architecture');
	selbox1.options[selbox1.options.length] = new Option('Area Studies','Area Studies');
	selbox1.options[selbox1.options.length] = new Option('Cognitive Science','Cognitive Science');
	selbox1.options[selbox1.options.length] = new Option('Conservation','Conservation');
	selbox1.options[selbox1.options.length] = new Option('Criminology','Criminology');
	selbox1.options[selbox1.options.length] = new Option('Cultural and Ethnic Studies','Cultural and Ethnic Studies');
	selbox1.options[selbox1.options.length] = new Option('Development Studies','Development Studies');
	selbox1.options[selbox1.options.length] = new Option('Emergency Management','Emergency Management');
	selbox1.options[selbox1.options.length] = new Option('Gender and Sexuality Studies','Gender and Sexuality Studies');
	selbox1.options[selbox1.options.length] = new Option('Geography','Geography');
	selbox1.options[selbox1.options.length] = new Option('Human Geography','Human Geography');
	selbox1.options[selbox1.options.length] = new Option('International Relations','International Relations');
	selbox1.options[selbox1.options.length] = new Option('Palliative Care','Palliative Care');
	selbox1.options[selbox1.options.length] = new Option('Parapsychology and Occult Sciences','Parapsychology and Occult Sciences');
	selbox1.options[selbox1.options.length] = new Option('Political Science','Political Science');
	selbox1.options[selbox1.options.length] = new Option('Population Studies','Population Studies');
	selbox1.options[selbox1.options.length] = new Option('Public Administration','Public Administration');
	selbox1.options[selbox1.options.length] = new Option('Public Health','Public Health');
	selbox1.options[selbox1.options.length] = new Option('Public Policy','Public Policy');
	selbox1.options[selbox1.options.length] = new Option('Social Epidemiology','Social Epidemiology');
	selbox1.options[selbox1.options.length] = new Option('Social Sciences (Others)','Social Sciences (Others)');
	selbox1.options[selbox1.options.length] = new Option('Social Welfare/Nursing','Social Welfare/Nursing');
	selbox1.options[selbox1.options.length] = new Option('Social Work','Social Work');
	selbox1.options[selbox1.options.length] = new Option('Sociology','Sociology');
	selbox1.options[selbox1.options.length] = new Option('Tourism Studies','Tourism Studies');
	selbox1.options[selbox1.options.length] = new Option('Transportation','Transportation');
	selbox1.options[selbox1.options.length] = new Option('Urban Studies','Urban Studies');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Art-Visual Arts") {	selbox1.options[selbox1.options.length] = new Option('Film Studies','Film Studies');
	selbox1.options[selbox1.options.length] = new Option('Painting/Sculpture','Painting/Sculpture');
	selbox1.options[selbox1.options.length] = new Option('Photography','Photography');
	selbox1.options[selbox1.options.length] = new Option('Visual Arts (Others)','Visual Arts (Others)');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Med-Alternative Medicine") {	selbox1.options[selbox1.options.length] = new Option('Acupuncture','Acupuncture');
	selbox1.options[selbox1.options.length] = new Option('Alternative Medicine','Alternative Medicine');
	selbox1.options[selbox1.options.length] = new Option('Ayurveda','Ayurveda');
	selbox1.options[selbox1.options.length] = new Option('Chiropractic Medicine ','Chiropractic Medicine ');
	selbox1.options[selbox1.options.length] = new Option('Herbalism ','Herbalism ');
	selbox1.options[selbox1.options.length] = new Option('Homeopathy ','Homeopathy ');
	selbox1.options[selbox1.options.length] = new Option('Naturopathy','Naturopathy');
	selbox1.options[selbox1.options.length] = new Option('Nutritional-based Therapies','Nutritional-based Therapies');
	selbox1.options[selbox1.options.length] = new Option('Traditional Chinese Medicine ','Traditional Chinese Medicine ');
	selbox1.options[selbox1.options.length] = new Option('Yoga ','Yoga ');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Med-Dentistry") {	selbox1.options[selbox1.options.length] = new Option('Dentistry (Others)','Dentistry (Others)');
	selbox1.options[selbox1.options.length] = new Option('Endodontics','Endodontics');
	selbox1.options[selbox1.options.length] = new Option('Forensic Dentistry','Forensic Dentistry');
	selbox1.options[selbox1.options.length] = new Option('General Dentistry','General Dentistry');
	selbox1.options[selbox1.options.length] = new Option('Oral & Maxillofacial Pathology','Oral & Maxillofacial Pathology');
	selbox1.options[selbox1.options.length] = new Option('Oral & Maxillofacial Surgery','Oral & Maxillofacial Surgery');
	selbox1.options[selbox1.options.length] = new Option('Orthodontics','Orthodontics');
	selbox1.options[selbox1.options.length] = new Option('Pediatric Dentistry','Pediatric Dentistry');
	selbox1.options[selbox1.options.length] = new Option('Periodontics','Periodontics');
	selbox1.options[selbox1.options.length] = new Option('Prosthodontics','Prosthodontics');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Med-Health Management") {	selbox1.options[selbox1.options.length] = new Option('Health Information Management','Health Information Management');
	selbox1.options[selbox1.options.length] = new Option('Healthcare Policies/Economics','Healthcare Policies/Economics');
	selbox1.options[selbox1.options.length] = new Option('Hospital Management/Administration','Hospital Management/Administration');
	selbox1.options[selbox1.options.length] = new Option('Public Health Management/Administration','Public Health Management/Administration');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Med-Medicine") {	selbox1.options[selbox1.options.length] = new Option('Allergology','Allergology');
	selbox1.options[selbox1.options.length] = new Option('Anatomy','Anatomy');
	selbox1.options[selbox1.options.length] = new Option('Andrology','Andrology');
	selbox1.options[selbox1.options.length] = new Option('Anesthesiology','Anesthesiology');
	selbox1.options[selbox1.options.length] = new Option('Audiology','Audiology');
	selbox1.options[selbox1.options.length] = new Option('Biomechanics','Biomechanics');
	selbox1.options[selbox1.options.length] = new Option('Cardiology','Cardiology');
	selbox1.options[selbox1.options.length] = new Option('Clinical Microbiology','Clinical Microbiology');
	selbox1.options[selbox1.options.length] = new Option('Community Medicine','Community Medicine');
	selbox1.options[selbox1.options.length] = new Option('Critical/Intensive Medicine','Critical/Intensive Medicine');
	selbox1.options[selbox1.options.length] = new Option('Dermatology','Dermatology');
	selbox1.options[selbox1.options.length] = new Option('Diabetology','Diabetology');
	selbox1.options[selbox1.options.length] = new Option('Emergency Medicine','Emergency Medicine');
	selbox1.options[selbox1.options.length] = new Option('Endocrinology','Endocrinology');
	selbox1.options[selbox1.options.length] = new Option('Epidemiology','Epidemiology');
	selbox1.options[selbox1.options.length] = new Option('Exercise Physiology','Exercise Physiology');
	selbox1.options[selbox1.options.length] = new Option('Forensic Medicine','Forensic Medicine');
	selbox1.options[selbox1.options.length] = new Option('Gastroenterology','Gastroenterology');
	selbox1.options[selbox1.options.length] = new Option('General Medicine','General Medicine');
	selbox1.options[selbox1.options.length] = new Option('Geriatrics & Gerontology','Geriatrics & Gerontology');
	selbox1.options[selbox1.options.length] = new Option('Hematology','Hematology');
	selbox1.options[selbox1.options.length] = new Option('Hepatology','Hepatology');
	selbox1.options[selbox1.options.length] = new Option('History of Medicine','History of Medicine');
	selbox1.options[selbox1.options.length] = new Option('Infectious Diseases','Infectious Diseases');
	selbox1.options[selbox1.options.length] = new Option('Internal Medicine','Internal Medicine');
	selbox1.options[selbox1.options.length] = new Option('Kinematics/Kinesiology','Kinematics/Kinesiology');
	selbox1.options[selbox1.options.length] = new Option('Medical Education','Medical Education');
	selbox1.options[selbox1.options.length] = new Option('Medical Ethics','Medical Ethics');
	selbox1.options[selbox1.options.length] = new Option('Medical Physics','Medical Physics');
	selbox1.options[selbox1.options.length] = new Option('Medical Statistics','Medical Statistics');
	selbox1.options[selbox1.options.length] = new Option('Medical Technology','Medical Technology');
	selbox1.options[selbox1.options.length] = new Option('Myology','Myology');
	selbox1.options[selbox1.options.length] = new Option('Nanomedicine','Nanomedicine');
	selbox1.options[selbox1.options.length] = new Option('Nephrology','Nephrology');
	selbox1.options[selbox1.options.length] = new Option('Neurology','Neurology');
	selbox1.options[selbox1.options.length] = new Option('Nuclear Medicine','Nuclear Medicine');
	selbox1.options[selbox1.options.length] = new Option('Nutrition','Nutrition');
	selbox1.options[selbox1.options.length] = new Option('Oncology','Oncology');
	selbox1.options[selbox1.options.length] = new Option('Ophthalmology','Ophthalmology');
	selbox1.options[selbox1.options.length] = new Option('Organ Transplantation','Organ Transplantation');
	selbox1.options[selbox1.options.length] = new Option('Orthopedics','Orthopedics');
	selbox1.options[selbox1.options.length] = new Option('Osteopathic Medicine','Osteopathic Medicine');
	selbox1.options[selbox1.options.length] = new Option('Otolaryngology','Otolaryngology');
	selbox1.options[selbox1.options.length] = new Option('Pain Medicine','Pain Medicine');
	selbox1.options[selbox1.options.length] = new Option('Palliative Medicine','Palliative Medicine');
	selbox1.options[selbox1.options.length] = new Option('Pediatrics','Pediatrics');
	selbox1.options[selbox1.options.length] = new Option('Physiology','Physiology');
	selbox1.options[selbox1.options.length] = new Option('Podiatry','Podiatry');
	selbox1.options[selbox1.options.length] = new Option('Psychiatry','Psychiatry');
	selbox1.options[selbox1.options.length] = new Option('Pulmonology/Respiratory Medicine','Pulmonology/Respiratory Medicine');
	selbox1.options[selbox1.options.length] = new Option('Rheumatology','Rheumatology');
	selbox1.options[selbox1.options.length] = new Option('Sexual Medicine','Sexual Medicine');
	selbox1.options[selbox1.options.length] = new Option('Sleep Medicine','Sleep Medicine');
	selbox1.options[selbox1.options.length] = new Option('Social Medicine','Social Medicine');
	selbox1.options[selbox1.options.length] = new Option('Sports Medicine & Technology','Sports Medicine & Technology');
	selbox1.options[selbox1.options.length] = new Option('Vascular Medicine','Vascular Medicine');
	selbox1.options[selbox1.options.length] = new Option('Veterinary Medicine','Veterinary Medicine');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Med-Nursing") {	selbox1.options[selbox1.options.length] = new Option('Family Nursing','Family Nursing');
	selbox1.options[selbox1.options.length] = new Option('Geriatric Nursing','Geriatric Nursing');
	selbox1.options[selbox1.options.length] = new Option('Home Health Nursing','Home Health Nursing');
	selbox1.options[selbox1.options.length] = new Option('Nursing','Nursing');
	selbox1.options[selbox1.options.length] = new Option('Palliative Nursing','Palliative Nursing');
	selbox1.options[selbox1.options.length] = new Option('Pediatric Nursing','Pediatric Nursing');
	selbox1.options[selbox1.options.length] = new Option('Perioperative Nursing','Perioperative Nursing');
	selbox1.options[selbox1.options.length] = new Option('Psychiatric and Mental Health Nursing','Psychiatric and Mental Health Nursing');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Med-Obstetrics and Gynecology") {	selbox1.options[selbox1.options.length] = new Option('Family Planning','Family Planning');
	selbox1.options[selbox1.options.length] = new Option('Gynecology','Gynecology');
	selbox1.options[selbox1.options.length] = new Option('Incontinence','Incontinence');
	selbox1.options[selbox1.options.length] = new Option('Infertility','Infertility');
	selbox1.options[selbox1.options.length] = new Option('Laparoscopy','Laparoscopy');
	selbox1.options[selbox1.options.length] = new Option('Obstetric/Gynecological Surgery','Obstetric/Gynecological Surgery');
	selbox1.options[selbox1.options.length] = new Option('Obstetrics ','Obstetrics ');
	selbox1.options[selbox1.options.length] = new Option('Obstetrics and Gynecology (Others)','Obstetrics and Gynecology (Others)');
	selbox1.options[selbox1.options.length] = new Option('Perinatology','Perinatology');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Med-Pathology") {	selbox1.options[selbox1.options.length] = new Option('Anatomical/Surgical Pathology','Anatomical/Surgical Pathology');
	selbox1.options[selbox1.options.length] = new Option('Clinical Pathology/Anatomical Pathology','Clinical Pathology/Anatomical Pathology');
	selbox1.options[selbox1.options.length] = new Option('Cytopathology','Cytopathology');
	selbox1.options[selbox1.options.length] = new Option('Digital Pathology','Digital Pathology');
	selbox1.options[selbox1.options.length] = new Option('Forensic Pathology ','Forensic Pathology ');
	selbox1.options[selbox1.options.length] = new Option('General Pathology','General Pathology');
	selbox1.options[selbox1.options.length] = new Option('Hematopathology','Hematopathology');
	selbox1.options[selbox1.options.length] = new Option('Histopathology','Histopathology');
	selbox1.options[selbox1.options.length] = new Option('Molecular Pathology','Molecular Pathology');
	selbox1.options[selbox1.options.length] = new Option('Pathology (Others)','Pathology (Others)');
	selbox1.options[selbox1.options.length] = new Option('Telepathology','Telepathology');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Med-Pharmacology") {	selbox1.options[selbox1.options.length] = new Option('Forensic toxicology','Forensic toxicology');
	selbox1.options[selbox1.options.length] = new Option('Pharmaceutical Toxicology','Pharmaceutical Toxicology');
	selbox1.options[selbox1.options.length] = new Option('Pharmacodynamics','Pharmacodynamics');
	selbox1.options[selbox1.options.length] = new Option('Pharmacokinetics','Pharmacokinetics');
	selbox1.options[selbox1.options.length] = new Option('Pharmacotherapy','Pharmacotherapy');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Med-Radiology/Imaging") {	selbox1.options[selbox1.options.length] = new Option('Interventional Radiology','Interventional Radiology');
	selbox1.options[selbox1.options.length] = new Option('Medical Imaging','Medical Imaging');
	selbox1.options[selbox1.options.length] = new Option('Radiobiology','Radiobiology');
	selbox1.options[selbox1.options.length] = new Option('Radiology/Imaging (Others)','Radiology/Imaging (Others)');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Med-Rehabilitation Sciences") {	selbox1.options[selbox1.options.length] = new Option('Ergonomics','Ergonomics');
	selbox1.options[selbox1.options.length] = new Option('Occupational Therapy','Occupational Therapy');
	selbox1.options[selbox1.options.length] = new Option('Physical Therapy','Physical Therapy');
	selbox1.options[selbox1.options.length] = new Option('Rehabilitation Sciences','Rehabilitation Sciences');
	selbox1.options[selbox1.options.length] = new Option('Speech/Audio Therapy','Speech/Audio Therapy');
selbox1.options[selbox1.options.length] = new Option('Other','Other');
} if (chosen == "Med-Surgery") {	selbox1.options[selbox1.options.length] = new Option('Cardiac/Cardiovascular Surgery','Cardiac/Cardiovascular Surgery');
	selbox1.options[selbox1.options.length] = new Option('Colorectal/Intestinal Surgery','Colorectal/Intestinal Surgery');
	selbox1.options[selbox1.options.length] = new Option('Emergency Surgery','Emergency Surgery');
	selbox1.options[selbox1.options.length] = new Option('General Surgery','General Surgery');
	selbox1.options[selbox1.options.length] = new Option('Minimally-invasive surgery','Minimally-invasive surgery');
	selbox1.options[selbox1.options.length] = new Option('Neurosurgery','Neurosurgery');
	selbox1.options[selbox1.options.length] = new Option('Orthopedic Surgery','Orthopedic Surgery');
	selbox1.options[selbox1.options.length] = new Option('Plastic & Reconstructive Surgery','Plastic & Reconstructive Surgery');
	selbox1.options[selbox1.options.length] = new Option('Remote Surgery','Remote Surgery');
	selbox1.options[selbox1.options.length] = new Option('Robot-assisted surgery','Robot-assisted surgery');
	selbox1.options[selbox1.options.length] = new Option('Surgery (Others)','Surgery (Others)');
	selbox1.options[selbox1.options.length] = new Option('Thoracic Surgery','Thoracic Surgery');
	selbox1.options[selbox1.options.length] = new Option('Transplant Surgery','Transplant Surgery');
	selbox1.options[selbox1.options.length] = new Option('Trauma Surgery','Trauma Surgery');
	selbox1.options[selbox1.options.length] = new Option('Urology','Urology');
	selbox1.options[selbox1.options.length] = new Option('Vascular Surgery','Vascular Surgery');
	selbox1.options[selbox1.options.length] = new Option('Other','Other');
}
}
function showother()
{
	if(document.frmSubmit.specialization.value == "Other")
	{
	document.frmSubmit.otherspecialization.disabled = false;
	}
	else
	{
	document.frmSubmit.otherspecialization.disabled = true;
	}
}
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}

function setOptions2(chosen)
{
var selbox5 = document.frmSubmit.R2;

selbox5.options.length = 1;

if(document.frmSubmit.R2.value == "Others")
{
	document.frmSubmit.txtRef.disabled = false;
}
else
{
	document.frmSubmit.txtRef.disabled = true;
	document.frmSubmit.txtRef.value = "";
}
//
if (chosen == "") {
document.getElementById("span1").innerHTML  = "";
document.frmSubmit.R2.disabled = true;
document.frmSubmit.txtRef.disabled = true;
document.frmSubmit.txtRef.value = "";
document.getElementById("message").style.display			= "none";
document.getElementById("message").style.visibility		= "hidden";
document.getElementById("r2").style.display			= "none";
document.getElementById("r2").style.visibility		= "hidden";
document.getElementById("txtref").style.display			= "none";
document.getElementById("txtref").style.visibility		= "hidden";
}
if (chosen == "Search Engine") {
selbox5.options[selbox5.options.length] = new Option('Google','Google');
selbox5.options[selbox5.options.length] = new Option('Yahoo','Yahoo');
selbox5.options[selbox5.options.length] = new Option('Bing (MSN)','Bing (MSN)');
selbox5.options[selbox5.options.length] = new Option('другие','Others');
document.frmSubmit.R2.disabled = false;
document.getElementById("span1").innerHTML  = "Поиск ключевых слов";
document.frmSubmit.txtRef.disabled = false;
document.getElementById("message").style.display			= "block";
document.getElementById("message").style.visibility		= "visible";
document.getElementById("r2").style.display			= "block";
document.getElementById("r2").style.visibility		= "visible";
document.getElementById("txtref").style.display			= "block";
document.getElementById("txtref").style.visibility		= "visible";
}
if (chosen == "Personal Referral") {
selbox5.options[selbox5.options.length] = new Option('Друзья Коллеги','Friend/Colleague');
selbox5.options[selbox5.options.length] = new Option('Университет/ Институт/ Организация','University/Institute/Organization');
document.frmSubmit.R2.disabled = false;
document.getElementById("span1").innerHTML  = "Название";
document.frmSubmit.txtRef.disabled = false;
document.getElementById("r2").style.display			= "block";
document.getElementById("r2").style.visibility		= "visible";
document.getElementById("message").style.display			= "block";
document.getElementById("message").style.visibility		= "visible";
document.getElementById("txtref").style.display			= "block";
document.getElementById("txtref").style.visibility		= "visible";
}
if (chosen == "Email Newsletters") {
document.frmSubmit.R2.disabled = true;
document.getElementById("span1").innerHTML  = "";
document.frmSubmit.txtRef.disabled = true;
document.frmSubmit.txtRef.value = "";
document.getElementById("message").style.display			= "none";
document.getElementById("message").style.visibility		= "hidden";
document.getElementById("r2").style.display			= "none";
document.getElementById("r2").style.visibility		= "hidden";
document.getElementById("txtref").style.display			= "none";
document.getElementById("txtref").style.visibility		= "hidden";
}
if (chosen == "Postal Mailings") {
document.frmSubmit.R2.disabled = true;
document.getElementById("span1").innerHTML  = "";
document.frmSubmit.txtRef.disabled = true;
document.frmSubmit.txtRef.value = "";
document.getElementById("message").style.display			= "none";
document.getElementById("message").style.visibility		= "hidden";
document.getElementById("r2").style.display			= "none";
document.getElementById("r2").style.visibility		= "hidden";
document.getElementById("txtref").style.display			= "none";
document.getElementById("txtref").style.visibility		= "hidden";
}
if (chosen == "Brochures") {
document.frmSubmit.R2.disabled = true;
document.getElementById("span1").innerHTML  = "";
document.frmSubmit.txtRef.disabled = true;
document.frmSubmit.txtRef.value = "";
document.getElementById("message").style.display			= "none";
document.getElementById("message").style.visibility		= "hidden";
document.getElementById("r2").style.display			= "none";
document.getElementById("r2").style.visibility		= "hidden";
document.getElementById("txtref").style.display			= "none";
document.getElementById("txtref").style.visibility		= "hidden";
}
if (chosen == "Advertisement Banner") {
document.frmSubmit.R2.disabled = true;
document.getElementById("span1").innerHTML  = "Укажите как вы нашли рекламу";
document.frmSubmit.txtRef.disabled = false;
document.getElementById("message").style.display			= "block";
document.getElementById("message").style.visibility		= "visible";
document.getElementById("r2").style.display			= "none";
document.getElementById("r2").style.visibility		= "hidden";
document.getElementById("txtref").style.display			= "block";
document.getElementById("txtref").style.visibility		= "visible";
}
if (chosen == "Website Link") {
document.frmSubmit.R2.disabled = true;
document.getElementById("span1").innerHTML  = ".Укажите, как вы нашли линк /URL";
document.frmSubmit.txtRef.disabled = false;
document.getElementById("message").style.display			= "block";
document.getElementById("message").style.visibility		= "visible";
document.getElementById("r2").style.display			= "none";
document.getElementById("r2").style.visibility		= "hidden";
document.getElementById("txtref").style.display			= "block";
document.getElementById("txtref").style.visibility		= "visible";
}
if (chosen == "Journal Recommendation") {
document.frmSubmit.R2.disabled = true;
document.getElementById("span1").innerHTML  = "Название журнала /URL";
document.frmSubmit.txtRef.disabled = false;
document.getElementById("message").style.display			= "block";
document.getElementById("message").style.visibility		= "visible";
document.getElementById("r2").style.display			= "none";
document.getElementById("r2").style.visibility		= "hidden";
document.getElementById("txtref").style.display			= "block";
document.getElementById("txtref").style.visibility		= "visible";
}
if (chosen == "Magazine Ads") {
document.frmSubmit.R2.disabled = true;
document.getElementById("span1").innerHTML  = "Название журнала";
document.frmSubmit.txtRef.disabled = false;
document.getElementById("message").style.display			= "block";
document.getElementById("message").style.visibility		= "visible";
document.getElementById("r2").style.display			= "none";
document.getElementById("r2").style.visibility		= "hidden";
document.getElementById("txtref").style.display			= "block";
document.getElementById("txtref").style.visibility		= "visible";
}
if (chosen == "Others") {
document.frmSubmit.R2.disabled = true;
document.getElementById("span1").innerHTML  = "Название/URL ";
document.frmSubmit.txtRef.disabled = false;
document.getElementById("message").style.display			= "block";
document.getElementById("message").style.visibility		= "visible";
document.getElementById("r2").style.display			= "none";
document.getElementById("r2").style.visibility		= "hidden";
document.getElementById("txtref").style.display			= "block";
document.getElementById("txtref").style.visibility		= "visible";
}
}