document.write('<div class=section1>');
document.write('<a id=discountbanner href=106.htm title=英文校正・英語論文校正・医学英文校正>');  
document.write('<span class=titledisc>');  
document.write('<strong class=txt14>英文校正最大</strong><strong class=perctext>20％ OFF!</strong>');
document.write('</span>');
document.write('<span class=discounttext>');
document.write('英文校正をご利用いただくお客様には、最大20％割引にて承ります（2011年6月15日まで）');
document.write('</span>');
document.write('</a>');
document.write('</div>');
